{"name": "test_bookmark_job", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.has url containing '/jobs'\n\nReason: AssertionError: actual url: https://www.workingnomads.com/users/profile\nScreenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.png\nPageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.html", "trace": "fn = <selene.core.conditions.BrowserCondition object at 0x0000026BFCE084D0>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.conditions.BrowserCondition object at 0x0000026BFCE084D0>, entity = <selene.core.entity.Browser object at 0x0000026BFCAFBBD0>\n\n    def __call__(self, entity: E) -> None:\n>       return self._fn(entity)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\condition.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nentity = <selene.core.entity.Browser object at 0x0000026BFCAFBBD0>\n\n    def fn(entity: E) -> None:\n        query_to_str = str(query)\n        result = (\n            query.__name__ if query_to_str.startswith('<function') else query_to_str\n        )\n        actual = query(entity)\n        if not predicate(actual):\n>           raise AssertionError(f'actual {result}: {actual}')\nE           AssertionError: actual url: https://www.workingnomads.com/users/profile\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\condition.py:146: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nlogin = <workingnomads_autotests_web.model.application.Application object at 0x0000026BFCB51CD0>\n\n    @allure.tag(\"web\")\n    @allure.feature(f'Bookmark')\n    @allure.story(\"First filter out jobs and add one of them to bookmarks\")\n    def test_bookmark_job(login):\n        with allure.step('Filter jobs by category, position type and key words'):\n>           app.main_page.verify_main_page() \\\n                .enter_key_words()\\\n                .filter_by_category()\\\n                .filter_by_position_type()\n\ntests\\test_job_bookmarks.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nworkingnomads_autotests_web\\model\\pages\\main_jobs_page.py:6: in verify_main_page\n    browser.should(have.url_containing('/jobs'))\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py:136: in should\n    self.wait.for_(condition)\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:143: in for_\n    return self._decorator(self)(logic)(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.conditions.BrowserCondition object at 0x0000026BFCE084D0>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_message = str(reason)\n    \n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=reason_message,\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 4s, while waiting for:\nE                   browser.has url containing '/jobs'\nE                   \nE                   Reason: AssertionError: actual url: https://www.workingnomads.com/users/profile\nE                   Screenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.png\nE                   PageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.html\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:141: TimeoutException"}, "steps": [{"name": "Filter jobs by category, position type and key words", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.has url containing '/jobs'\n\nReason: AssertionError: actual url: https://www.workingnomads.com/users/profile\nScreenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.png\nPageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1689624584712\\1689624584712.html\n\n", "trace": "  File \"C:\\Users\\skmee\\PycharmProjects\\workingnomads_autotests_web\\tests\\test_job_bookmarks.py\", line 11, in test_bookmark_job\n    app.main_page.verify_main_page() \\\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\PycharmProjects\\workingnomads_autotests_web\\workingnomads_autotests_web\\model\\pages\\main_jobs_page.py\", line 6, in verify_main_page\n    browser.should(have.url_containing('/jobs'))\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py\", line 136, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py\", line 143, in for_\n    return self._decorator(self)(logic)(fn)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1689624631391, "stop": 1689624635602}], "start": 1689624631390, "stop": 1689624635628, "uuid": "4599c5a1-2b1d-4cf3-9e25-412e13f95cd7", "historyId": "45125bd1a87fee0039ea6640587c5815", "testCaseId": "26389278e94a97283df77bb20091559b", "fullName": "tests.test_job_bookmarks#test_bookmark_job", "labels": [{"name": "feature", "value": "Bookmark"}, {"name": "story", "value": "First filter out jobs and add one of them to bookmarks"}, {"name": "tag", "value": "web"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_job_bookmarks"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "21168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_job_bookmarks"}]}